- hosts: 127.0.0.1
  connection: local

  vars_files:
  - vars/main.yml

  tasks:
  - name: Install Packages
    become: true
    dnf: name={{ item }} state=latest
    with_items:
      - npm
      - node
      - git

  - name: Install pm2
    become: true
    npm: name=pm2 global=yes production=yes

  - name: Create APP Directory
    file: path={{homeDir}}/{{appDir}} state=directory

  - name: Copy Private Key
    copy: src={{privateKey}} dest={{homeDir}} mode=0600

  - name: Git Clone Repo
    git: repo=git@github.com:{{account}}/{{repo}}.git dest={{homeDir}}/{{appDir}} update=yes force=yes accept_hostkey=yes key_file={{homeDir}}/id_rsa
    register: git_finished

  - name: Running NPM install
    npm: path={{homeDir}}/{{appDir}}/backened
    register: npm_finished

  - name: Stop APP
    sudo_user: jforero
    command: pm2 stop app chdir={{homeDir}}/{{appDir}}
    ignore_errors: yes

  - name: Start APP
    sudo_user: jforero
    command: pm2 start index.js --name app chdir={{homeDir}}/{{appDir}}
    ignore_errors: yes
